In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('SMSSpamCollection.csv', sep='\t', header=None, encoding='latin-1')

In [3]:
df.rename(columns={0: 'Category', 1: 'message'}, inplace=True)

In [4]:
df.head()

Category                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
df['spam'] = df['Category'].replace(['spam', 'ham'], [1, 0])

In [6]:
df.head()

Category                                            message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [7]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
trainX, testX, trainY, testY = train_test_split(df['message'], df['spam'], train_size=0.75, test_size=0.25, random_state=40)

In [9]:
countVec = CountVectorizer()
count = countVec.fit_transform(trainX.values)
print(count.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [10]:
model = MultinomialNB()
model.fit(count, trainY)

MultinomialNB()

In [11]:
email = [
    "SALE! SALE! SALE! 50% OFF",
    "SALE! SALE! SALE! 50% OFF"
]
count = countVec.transform(email)
model.predict(count)

array([1, 1], dtype=int64)

In [12]:
testcount = countVec.transform(testX.values)
y = model.score(testcount, testY)

In [13]:
print('Score :', y)

Score : 0.9842067480258435


In [14]:
print(count.shape)

(2, 7524)


In [15]:
trainX.shape

(4179,)