In [3]:
import numpy as np

In [16]:
arr1 = np.array([1,2,3,4,5,6,7,8,9], dtype=np.int64)
arr2 = np.array([9,8,7,6,5,4,3,2,1], dtype=np.int64)


[1 2 3 4 5 6 7 8 9] [9 8 7 6 5 4 3 2 1]


In [32]:
arr1 = arr1.reshape(3,3)
arr2 = arr2.reshape(3,3)

print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [37]:
res1 = np.multiply(arr1, arr2)

In [38]:
res2 = arr1 * arr2

In [43]:
res1 == res2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [46]:
np.array_equal(res1, res2)

True

In [52]:
arr3 = np.ones([4,4], dtype=np.int64)

In [59]:
arr4 = np.zeros([3,3], dtype=np.int64)

In [64]:
arr5 = np.eye(10)

In [94]:
import time
size = 1000
lmat1 = np.random.randint(100, size =[size, size]).tolist()
lmat2 = np.random.randint(100, size =[size, size]).tolist()
lres1 = np.zeros((size, size), dtype=np.int64).tolist()

print("start", time.time())
for i in range(size):
    for j in range(size):
        for k in range(size):
            lres1[i][j] += lmat1[i][k] * lmat2[k][j]
            
print("done", time.time())

start 1658744429.0862958
done 1658744653.2536683


In [95]:
t = 1658744653.2536683 - 1658744429.0862958

In [97]:
print(t / 60)

3.7361228744188946


In [100]:
import time
size = 1000
mat1 = np.random.randint(100, size =[size, size])
mat2 = np.random.randint(100, size =[size, size])

start = time.time()
mres1 = mat1 * mat2
done = time.time()
print((done - start)/60)

3.56594721476237e-05


In [104]:
import time
size = 1000
mat1 = np.random.randint(100, size =[size, size])
mat2 = np.random.randint(100, size =[size, size])

start = time.time()
mres1 = np.multiply(mat1, mat2)
done = time.time()
print((done - start)/60)

3.235340118408203e-05


In [27]:
arr = np.array([10,20,30,40,50,11,22,33,44,55])
for i in range(len(arr)):
    if(i&1):
        print(arr[i], end=' ')

20 40 11 33 55 

In [28]:
odd = arr[1: len(arr): 2]
print(arr)
print(odd)

[10 20 30 40 50 11 22 33 44 55]
[20 40 11 33 55]


In [52]:
arr.resize([5,2])
print(arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [58]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr.resize([3,2,2])
print(arr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [65]:
np.reshape(arr, [6,2])

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [66]:
print(arr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [79]:
?np.where()

In [93]:
arr = np.array([1,2,3,4,5,6,7,8,12,10,11,12])
i = np.arange(0,len(arr))

In [95]:
np.where(i & 1, arr[i], 0)

array([ 0,  2,  0,  4,  0,  6,  0,  8,  0, 10,  0, 12])

In [97]:
import pandas as pd

In [101]:
df = pd.read_csv('business-financial-data-mar-2022-quarter-csv.csv')

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5715 entries, 0 to 5714
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Series_reference  5715 non-null   object 
 1   Period            5715 non-null   float64
 2   Data_value        5401 non-null   float64
 3   Suppressed        294 non-null    object 
 4   STATUS            5715 non-null   object 
 5   UNITS             5715 non-null   object 
 6   Magnitude         5715 non-null   int64  
 7   Subject           5715 non-null   object 
 8   Group             5715 non-null   object 
 9   Series_title_1    5715 non-null   object 
 10  Series_title_2    5715 non-null   object 
 11  Series_title_3    5715 non-null   object 
 12  Series_title_4    5715 non-null   object 
 13  Series_title_5    0 non-null      float64
dtypes: float64(3), int64(1), object(10)
memory usage: 625.2+ KB


In [108]:
df.head(15).tail(5)

Series_reference   Period  Data_value Suppressed STATUS    UNITS  \
10    BDCQ.SF1AA2CA  2018.12    1570.507        NaN      F  Dollars   
11    BDCQ.SF1AA2CA  2019.03    1393.749        NaN      F  Dollars   
12    BDCQ.SF1AA2CA  2019.06    1517.143        NaN      F  Dollars   
13    BDCQ.SF1AA2CA  2019.09    1381.514        NaN      F  Dollars   
14    BDCQ.SF1AA2CA  2019.12    1370.985        NaN      F  Dollars   

    Magnitude                         Subject  \
10          6  Business Data Collection - BDC   
11          6  Business Data Collection - BDC   
12          6  Business Data Collection - BDC   
13          6  Business Data Collection - BDC   
14          6  Business Data Collection - BDC   

                                              Group            Series_title_1  \
10  Industry by financial variable (NZSIOC Level 2)  Sales (operating income)   
11  Industry by financial variable (NZSIOC Level 2)  Sales (operating income)   
12  Industry by financial variable (NZSIOC Level 2)  Sales (operating income)   
13  Industry by financial variable (NZSIOC Level 2)  Sales (operating income)   
14  Industry by financial variable (NZSIOC Level 2)  Sales (operating income)   

          Series_title_2  Series_title_3 Series_title_4  Series_title_5  
10  Forestry and Logging  Current prices     Unadjusted             NaN  
11  Forestry and Logging  Current prices     Unadjusted             NaN  
12  Forestry and Logging  Current prices     Unadjusted             NaN  
13  Forestry and Logging  Current prices     Unadjusted             NaN  
14  Forestry and Logging  Current prices     Unadjusted             NaN

In [116]:
df['Data_value'].mean()

4687.586514534346

In [126]:
df.fillna(value=369, inplace=True)